[package]
name = "license-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["cargo", "derive"] }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
serde_json = "1.0.127"
